model: DeepAnT
dataset: ASD
paradigm: FL
model_params:
  seq_dim: 300
  feat_dim: 19
  kernel_dim_1: 7
  kernel_dim_2: 5
  pull_dim: 2
  pred_horizon: 1
  lr: 0.007
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 60
  local_epochs: 5
  num_edge_nodes: 5
  win_size: 300
  win_stride: 1
  total_nodes: 12
