model: DeepAnT
dataset: QAPPD
paradigm: CL
model_params:
  seq_dim: 120
  feat_dim: 14
  kernel_dim_1: 3
  kernel_dim_2: 5
  pull_dim: 2
  pred_horizon: 1
  lr: 0.001
  optimizer: Adam
train_params:
  epochs: 10
  batch_size: 1024
  win_size: 120
  win_stride: 120
  total_nodes: 10
