model: DeepAnT
dataset: QAPPD
paradigm: FL
model_params:
  seq_dim: 50
  feat_dim: 14
  kernel_dim_1: 3
  kernel_dim_2: 9
  pull_dim: 2
  pred_horizon: 1
  lr: 0.0003
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 50
  local_epochs: 5
  num_edge_nodes: 3
  win_size: 50
  win_stride: 15
  total_nodes: 10
