model: DeepAnT
dataset: QAPPD
paradigm: CL
model_params:
  seq_dim: 250
  feat_dim: 14
  kernel_dim_1: 11
  kernel_dim_2: 5
  pull_dim: 2
  pred_horizon: 1
  lr: 0.01
  optimizer: Adam
train_params:
  epochs: 68
  batch_size: 1024
  win_size: 250
  win_stride: 75
  total_nodes: 10
