model: DeepAnT
dataset: ASD
paradigm: H-FL
model_params:
  seq_dim: 300
  feat_dim: 19
  kernel_dim_1: 3
  kernel_dim_2: 7
  pull_dim: 2
  pred_horizon: 1
  lr: 0.001
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 85
  local_epochs: 3
  num_edge_nodes: 4
  num_fog_servers: 2
  win_size: 300
  win_stride: 1
  total_nodes: 12
