model: DeepAnT
dataset: ASD
paradigm: FL
model_params:
  seq_dim: 120
  feat_dim: 19
  kernel_dim_1: 5
  kernel_dim_2: 7
  pull_dim: 2
  pred_horizon: 1
  lr: 0.0005
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 50
  local_epochs: 3
  num_edge_nodes: 5
  win_size: 120
  win_stride: 120
  total_nodes: 12
