model: DeepAnT
dataset: ASD
paradigm: H-FL
model_params:
  seq_dim: 20
  feat_dim: 19
  kernel_dim_1: 5
  kernel_dim_2: 7
  pull_dim: 2
  pred_horizon: 1
  lr: 0.0005
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 10
  local_epochs: 3
  num_edge_nodes: 3
  num_fog_servers: 2
  win_size: 20
  win_stride: 20
  total_nodes: 12
