model: LSTMAE
dataset: ASD
paradigm: CL
model_params:
  seq_dim: 300
  feat_dim: 19
  lat_dim: 14
  num_layer: 1
  dropout: 0.0
  pooling: mean
  lr: 0.01
  optimizer: Adam
train_params:
  epochs: 80
  batch_size: 1024
  win_size: 300
  win_stride: 1
  total_nodes: 12
