model: LSTMAE
dataset: ASD
paradigm: FL
model_params:
  seq_dim: 300
  feat_dim: 19
  lat_dim: 8
  num_layer: 1
  dropout: 0.0
  pooling: mean
  lr: 0.01
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 50
  local_epochs: 3
  num_edge_nodes: 3
  win_size: 300
  win_stride: 1
  total_nodes: 12
