model: MTADGAT
dataset: QAPPD
paradigm: H-FL
model_params:
  seq_len: 300
  feat_len: 14
  embed_dim: 10
  embed_dim_2: 128
  conv_dim: 15
  batch_size: 1024
  gamma: 0.8
  lr: 0.003
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 50
  local_epochs: 4
  num_edge_nodes: 3
  num_fog_servers: 2
  win_size: 300
  win_stride: 90
  total_nodes: 10
