model: MTADGAT
dataset: ASD
paradigm: FL
model_params:
  seq_len: 120
  feat_len: 19
  embed_dim: 8
  embed_dim_2: 32
  conv_dim: 3
  batch_size: 1024
  gamma: 0.8
  lr: 0.0005
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 10
  local_epochs: 3
  num_edge_nodes: 3
  win_size: 120
  win_stride: 120
  total_nodes: 12
