model: MTADGAT
dataset: ASD
paradigm: CL
model_params:
  seq_len: 300
  feat_len: 19
  embed_dim: 10
  embed_dim_2: 128
  conv_dim: 11
  batch_size: 1024
  gamma: 0.8
  lr: 0.007
  optimizer: Adam
train_params:
  epochs: 50
  batch_size: 1024
  win_size: 300
  win_stride: 90
  total_nodes: 12
