model: TranAD
dataset: ASD
paradigm: CL
model_params:
  seq_dim: 300
  feat_dim: 19
  lat_dim: 8
  dropout: 0.1
  lr: 0.007
  w_decay: 0.00001
  optimizer: Adam
train_params:
  epochs: 50
  batch_size: 1024
  win_size: 300
  win_stride: 1
  total_nodes: 12
