model: TranAD
dataset: ASD
paradigm: FL
model_params:
  seq_dim: 300
  feat_dim: 19
  lat_dim: 16
  dropout: 0.1
  lr: 0.001
  w_decay: 0.0001
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 50
  local_epochs: 5
  num_edge_nodes: 5
  win_size: 300
  win_stride: 1
  total_nodes: 12
