model: TranAD
dataset: QAPPD
paradigm: H-FL
model_params:
  seq_dim: 200
  feat_dim: 14
  lat_dim: 12
  dropout: 0.1
  lr: 0.001
  w_decay: 0.0001
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 95
  local_epochs: 3
  num_edge_nodes: 3
  num_fog_servers: 2
  win_size: 200
  win_stride: 60
  total_nodes: 10
