model: TranAD
dataset: QAPPD
paradigm: CL
model_params:
  seq_dim: 200
  feat_dim: 14
  lat_dim: 10
  dropout: 0.1
  lr: 0.01
  w_decay: 0.00001
  optimizer: Adam
train_params:
  epochs: 50
  batch_size: 1024
  win_size: 200
  win_stride: 60
  total_nodes: 10
