model: USAD
dataset: QAPPD
paradigm: FL
model_params:
  seq_dim: 120
  feat_dim: 14
  lat_dim: 64
  lr: 0.001
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 50
  local_epochs: 3
  num_edge_nodes: 5
  win_size: 120
  win_stride: 120
  total_nodes: 10
