model: USAD
dataset: ASD
paradigm: CL
model_params:
  seq_dim: 300
  feat_dim: 19
  lat_dim: 128
  lr: 0.0003
  optimizer: Adam
train_params:
  epochs: 10
  batch_size: 1024
  win_size: 300
  win_stride: 1
  total_nodes: 12
