model: USAD
dataset: QAPPD
paradigm: FL
model_params:
  seq_dim: 300
  feat_dim: 14
  lat_dim: 128
  lr: 0.007
  optimizer: SGD
train_params:
  batch_size: 1024
  num_server_rounds: 50
  local_epochs: 5
  num_edge_nodes: 3
  win_size: 300
  win_stride: 90
  total_nodes: 10
